import "./globals.scss";
import type { Metadata } from "next";
import { IBM_Plex_Sans } from "next/font/google";
import type { MenuItem } from "./components/Header";
import Header from "./components/Header";

const ibm_plex_sans = IBM_Plex_Sans({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const menuItems: Array<MenuItem> = [
  { name: "Home", href: "/", key: "home" },
  { name: "Link 1", href: "/link1", key: "link1" },
  { name: "Link 2", href: "/link2", key: "link2" },
  { name: "Link 3", href: "/link3", key: "link3" },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={ibm_plex_sans.className}>
        <Header
          title="Carbon Design System"
          prefix="Carbon"
          name="[Design System]"
          menuItems={menuItems}
        />
        {children}
      </body>
    </html>
  );
}
